### ISSUE TITLE
Questions about the samples with record=1

### ISSUE THREAD

**Issue by badbadcode** [Light-jason/Code-of-4S-shop-customer-churn-prediction#2]
您好：

 请问论文里介绍的样本数目（26,640 negative (absence) samples and 119,183 positive (presence)）是包括record=1的数据吗？如果包括的话，为何报告confusion set时，不去除record=1的样本呢（因为本身模型并没有预测这些样本）？

若理解有误，还请纠正~

**Comment by badbadcode** [comment]
3. 在tuneModifiedRNNver2.m中，传入modifyRNN_for_4Sver2的seq_train已经去除了record=1的记录，那么对于训练集里record=2的数据，没办法训练呀？

**Comment by Light-jason** [comment]
同学，您好
很高兴收到你对于我们论文以及代码的疑问，这是对于我们的肯定。
以下是我对您提出的问题的解答：
（1）第一问中，实际上我们在构建程序所使用的数据集时，是与论文描述的一致的。也就是说同一行的x和y并不是同一个时间步，x是上个时刻，y是当前时刻。因此seq_len=1时，是正确的。
（2）我们在论文中是将presence设置为类别1即正例，absence设置为类别0即负例。混淆矩阵的目的是反映模型对正负样本的预测情况，因此在构建confusion matrix时不需要将record=1的去除。
（3）文章中实际上只有0,1两个类别，不存在record=2的情况。
若对回复有其他疑问，可以随时交流。
感谢您对我们工作的认可。
此致。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Light-jason/Code-of-4S-shop-customer-churn-prediction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 晚上8:44
收件人:&nbsp;"Light-jason/Code-of-4S-shop-customer-churn-prediction"<Code-of-4S-shop-customer-churn-prediction@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Light-jason/Code-of-4S-shop-customer-churn-prediction] Questions about the number of samples (#2)





 
您好：
  
关于modifyRNN_for_4Sver2函数：
   seq_len = min([record_train(n)-2,T]) + 1;  x_n = warr_train(n-seq_len+1:n,:);  y_n = y_train(n,1);
 如: 当 record_train(n)= 2 时，seq_len = 1，此时，x_n = warr_train(n)， 这是不合理的呀，因为实际应用时，预测 y_n 不会知道此时的 warr_train(n)， 而且，这也与论文里介绍不符：
   
a sample is denoted as (𝑥(𝑖)_𝑡−1,𝑦(𝑖)_𝑡 )
   
请问论文里介绍的样本数目（26,640 negative (absence) samples and 119,183 positive (presence)）是包括record=1的数据吗？如果包括的话，为何报告confusion set时，不去除record=1的样本呢（因为本身模型并没有预测这些样本）？
  
若理解有误，还请纠正~

**Comment by badbadcode** [comment]
谢谢您的解答！
 "同一行的x和y并不是同一个时间步"，就都可以解释的通了！
  关于混淆矩阵，我还有一个疑问，我根据代码猜测record 代表某个用户的时间 index，modifyRNN_for_4Sver2.m代码的第二行注释中提到`% modifyRNN_for_4Sver2的数据集去掉了record=1` ，也就是说，输入RNN的数据已经删去了每个用户 t1 时刻的记录，那么， tuneModifiedRNNver2.m 中交叉验证后得到的预测结果应该是不包括每个用户的t1时刻数据的，可是论文报告中的混淆矩阵的样本量仍然是所有的样本总数？

**Comment by Light-jason** [comment]
你好，关于这个问题。论文里提到的样本总数实际上已经是去掉每个用户的t1时刻记录后的总数，在原始数据集里是161186条记录，论文里是145823 也就是去掉了15363个用户的首条记录。论文里并没有提及到此过程，造成您的疑惑了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Light-jason/Code-of-4S-shop-customer-churn-prediction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 下午4:28
收件人:&nbsp;"Light-jason/Code-of-4S-shop-customer-churn-prediction"<Code-of-4S-shop-customer-churn-prediction@noreply.github.com&gt;;
抄送:&nbsp;"你在天堂遇到的五个人"<125207822@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Light-jason/Code-of-4S-shop-customer-churn-prediction] Questions about the samples with record=1 (#2)





 
谢谢您的解答！
 "同一行的x和y并不是同一个时间步"，就都可以解释的通了！
 关于混淆矩阵，我还有一个疑问，我根据代码猜测record 代表某个用户的时间 index，modifyRNN_for_4Sver2.m代码的第二行注释中提到% modifyRNN_for_4Sver2的数据集去掉了record=1 ，也就是说，输入RNN的数据已经删去了每个用户 t1 时刻的记录，那么， tuneModifiedRNNver2.m 中交叉验证后得到的预测结果应该是不包括每个用户的t1时刻数据的，可是论文报告中的混淆矩阵的样本量仍然是所有的样本总数？

**Comment by badbadcode** [comment]
明白了，谢谢。
